stages:
    - preparation
    - testing

composer:
    stage: preparation
    variables:
        COMPOSER_AUTH: |

    script:
        - php --version
        - composer config -g gitlab-oauth.git.netresearch.de $GITLAB_ACCESS_TOKEN
        - composer install --prefer-dist --no-ansi --no-interaction --no-progress --no-scripts
    artifacts:
        paths:
            - vendor/
            - public/
        expire_in: 1 days
        when: always
    cache:
        paths:
            - vendor/
            - public/


phplint:
    stage: testing
    extends:
        - .php
    needs:
        - composer
    script:
        - composer ci:test:php:lint

phpstan:
    stage: testing
    script:
        - php --version
        - vendor/bin/phpstan analyse --error-format=junit --no-progress -c Build/phpstan.neon > phpstan-report.xml
    artifacts:
        reports:
            junit:
                - phpstan-report.xml


rector:
    stage: testing
    extends:
        - .php
    needs:
        - composer
    script:
        - composer ci:test:php:rector

coding-style:
    stage: testing
    extends:
        - .php
    needs:
        - composer
    script:
        - composer ci:cgl -- --dry-run